### ISSUE TITLE
Encoding issues causes exception with psfdeflang

### ISSUE THREAD

**Issue by devosb** [silnrsi/fonttools#1]
When building the language specific variants of [Padauk](https://github.com/silnrsi/font-padauk) `psfdeflang` is called with causes an exception in [fontTools](https://github.com/fonttools/fonttools).
```
  File "/home/fontdev/.local/lib/python3.6/site-packages/fonttools-3.32.0-py3.6.egg/fontTools/ttLib/tables/S__i_l_l.py", line 49, in compile
    ldat += struct.pack(">4sHH", c.encode('utf8'), len(inf), 8 * (offset + len(self.langs) + 1))
AttributeError: 'bytes' object has no attribute 'encode'
```
fontTools (using the link above) and pysilfont was updated from source as of yesterday.

**Comment by devosb** [comment]
Seems to work with fontTools 4.3.0, it looks like I did not have the latest version after all.
